$(function(){
  var radio = {
    name: "Radio Waves",
    WavelengthRange: "1 m - 100 km",
    begins: 1,
    ends: 100*1e+3
  };

  var micro = {
    name: "Microwaves",
    WavelengthRange: "1 mm - 1 m",
    begins: 1*10e-3,
    ends: 1
  };

  var infrared = {
    name: "Infrared Radiation",
    WavelengthRange: "700 nm - 1 mm",
    begins: 700*10e-9,
    ends: 1*10e-3
  };

  var visible = {
    name: "Visible Light",
    WavelengthRange: "400 nm - 700 nm",
    begins: 400*10e-9,
    ends: 700*10e-9
  };

  var uva = {
    name: "Ultraviolet Type A Radiation",
    WavelengthRange: "315 nm - 400 nm",
    begins: 315*10e-9,
    ends: 400*10e-9
  };

  var uvb = {
    name: "Ultraviolet Type B Radiation",
    WavelengthRange: "280 nm - 315 nm",
    begins: 280*10e-9,
    ends: 315*10e-9
  };

  var uvc = {
    name: "Ultraviolet Type C Radiation",
    WavelengthRange: "100 nm - 280 nm",
    begins: 100*10e-9,
    ends: 280*10e-9
  };

  var euv = {
    name: "Extreme Ultraviolet Radiation",
    WavelengthRange: "10 nm - 100 nm",
    begins: 10*10e-9,
    ends: 100*10e-9
  };

  var uv = {
    name: "Ultraviolet Radiation",
    WavelengthRange: "10 nm - 400 nm",
    begins: 10*10e-9,
    ends: 400*10e-9
  };

  var xray = {
    name: "X-Rays",
    WavelengthRange: "10 pm - 10 nm",
    begins: 10*10e-12,
    ends: 10*10e-9
  };

  var gamma = {
    name: "Gamma Rays",
    WavelengthRange: "< 10 pm",
    begins: 10e-15,
    ends: 10*10e-12
  };

  var red = {
    name: "red",
    begins: 620*10e-9,
    ends: 740*10e-9,
    WavelengthRange: "620 nm - 740 nm"
  };

  var orange = {
    name: "orange",
    begins: 590*10e-9,
    ends: 620*10e-9,
    WavelengthRange: "590 nm - 620 nm"
  };

  var yellow = {
    name: "yellow",
    begins: 570*10e-9,
    ends: 590*10e-9,
    WavelengthRange: "570 nm - 590 nm"
  };

  var green = {
    name: "green",
    begins: 495*10e-9,
    ends: 570*10e-9,
    WavelengthRange: "495 nm - 570 nm"
  };

  var blue = {
    name: "blue",
    begins: 450*10e-9,
    ends: 495*10e-9,
    WavelengthRange: "450 nm - 495 nm"
  };

  var violet = {
    name: "violet",
    begins: 310*10e-9,
    ends: 450*10e-9,
    WavelengthRange: "310 nm - 450 nm"
  };

  var descriptions = {};
  descriptions["radio"] = "Radio waves today are often generated by manufactured devices. Radio waves' most self-explanator application comes from allowing us to tune into radio stations. Less well known applications of radio waves include early color televisions and cell phone signals. The wavelength of radio waves generally ranges between " + radio.WavelengthRange + ".";
  descriptions["micro"] = "Microwaves, like radio waves, are also often generated today be manufactured devices. However, most warm bodies emit tiny amounts of microwave radiation, also known as black body radiation. Microwaves are often used in one-to-one communication as opposed to radio waves, which are used in broadcast communication. In addition to being used inside microwave ovens, microwaves are also used in wireless data transfer such as Bluetooth, Wi-Fi, GPS, and radar technology. The wavelength of microwaves generally ranges between " + micro.WavelengthRange + ".";
  descriptions["infrared"] = "Infrared radiation is commonly felt as heat. It is most commonly released from the sun, but also has industrial applications such as fiber optic cables (ultra-fast internet), night vision, thermal imaging, and even heat seeking missiles. Infrared radiation from the sun is commonly absorbed by Carbon Dioxide in the atmosphere and water. However, it has little effect on biological systems. The wavelength of infrared waves generally ranges between " + infrared.WavelengthRange + ".";
  descriptions["uvalin"] = "Commonly known as black light, UVA radiation is radiation that reaches the Earth's surface. Unlike UVB and UVC radiation, UVA radiation is not absorbed by the Earth's ozone layer. The wavelength of UV A waves generally ranges between " + uva.WavelengthRange + ".";
  descriptions["uvblin"] = "UVB radiation acts as a transition between UVA and UVC radiation. It is mostly absorbed by the Earth's ozone layer. The wavelength of UVB waves generally ranges between " + uvb.WavelengthRange + ".";
  descriptions["uvclin"] = "UVC radiation is high frequency UV radiation that is completely absorbed by the Earth's atmosphere. It also has industrial applications in disinfection, and is often used for food protection, water sterilization, air disinfection, and wastewater treatment. The wavelength of UVC waves generally ranges between " + uvc.WavelengthRange + ".";
  descriptions["euvlin"] = "EUV rays are also known as ionizing radiation because of the effect that they have on commonly occurring elements such as Oxygen, which gets converted to Ozone because of the high energy associated with EUV rays. All electromagnetic waves with a wavelength shorter than that of Extreme Ultraviolet Radiation are known as ionizing radiation. The wavelength of EUV waves generally ranges between " + euv.WavelengthRange + ".";
  descriptions["xray"] = "X-rays are commonly known for being used in medicine to get images of things like dental alignments, bone fractures, and bone shape. X-rays are generated from high energy electron interactions. Although Wilhelm Conrad Rontgen is credited with the discovery, for which he received a Nobel Prize, much of the early work was also independently pioneered by Tesla, who managed to make much higher resolution and clearer photographs than were available at the time. Roentgen famously sent Tesla a letter thanking him for sending those photographs, writing 'If only I knew how you make such things!' The wavelength of X-Rays generally ranges between " + xray.WavelengthRange + ".";
  descriptions["gamma"] = "Gamma rays are often formed by radioactive decay in the nucleus of an atom. They have extremely high energy levels associated with them. Artificial sources of gamma rays include nuclear fission and fusion reactions. Natural sources include naturally occurring radioactive isotopes, lightning strikes, and a large number of phenomenon in outer space, such as explosions of giant stars that result in the formations of black holes or white dwarfs. The wavelength of gamma waves is generally " + gamma.WavelengthRange + ".";
  descriptions["uv"] = "Ultraviolet light has many applications ranging from counterfeit prevention, sanitation, and creating fluorescent and glowing colors! Some sources of ultraviolet light, especially high-frequency UV rays, can be harmful. These are emitted by the Sun, but are blocked by Earth's atmosphere, specifically the Ozone Layer. The wavelength of Ultraviolet light generally ranges between " + uv.WavelengthRange + ".";
  descriptions["visible"] = "Visible light is made up of all of the light that can be seen by human beings. It can be further broken down into all of the colors of the rainbow that can be seen when light is scattered, either through a prism or when sunlight scatters after rainfall. The wavelength of visible light generally ranges between " + visible.WavelengthRange + ".";
  descriptions["red"] = "Red light occurs on the edge of the visible light spectrum. EM waves with a larger wavelength than red light are considered infrared radiation. Red is a common color for laser technology. Early lasers used red light at 660 nm, whereas more recent ones emit red light at 671 nm. It is a color of fire, passion, and danger. It is also the most common primary color. Red light typically ranges from " + red.WavelengthRange + ".";
  descriptions["orange"] = "Orange is the one color that is named after a fruit. The reason these fruits are orange is because of carotene, an orange-colored pigment that helps plants photosynthesize and convert sunlight into energy, similar to chlorophyll. Orange light typically occurs between " + orange.WavelengthRange + ".";
  descriptions["yellow"] = "Yellow is the one color that has the shortest range of wavelengths on the visible light spectrum. It is often a primary color used by printers and painters. Yellow light occurs on the electromagnetic spectrum between " + yellow.WavelengthRange + ".";
  descriptions["green"] = "Green light is also commonly used in lasers. The most common wavelength of laser light is 532 nm. Many plants and trees in nature are colored green because of chlorophyll, which absorbs all sunlight, but reflects green light. Green light occurs on the electromagnetic spectrum between " + green.WavelengthRange + ".";
  descriptions["blue"] = "Blue lasers are often used in writing and storing information to optical discs more efficiently, which was popularized with the advent of Blu-ray technology. The blue lasers widely available to the public generally have a wavelength between 445 nm and 447 nm. Blue light is also the light that is most susceptible to scattering on Earth, which results in a blue sky as well as a blue ocean. Indigo is considered a variation of blue, which is why it is not shown on the visible light spectrum. Blue light occurs on the electromagnetic spectrum between " + blue.WavelengthRange + ".";
  descriptions["violet"] = "Violet light occurs towards the high-frequency end of the visible light spectrum, beyond which lies ultraviolet light. As a result, it has the shortest wavelength among all the visible colors. Visible violet light typically occurs between " + violet.WavelengthRange + ".";
  
  var names = {};
  names["radio"] = "Radio Waves";
  names["micro"] = "Microwaves";
  names["infrared"] = "Infrared Radiation";
  names["visible"] = "Visible Light";
  names["uv"] = "Ultraviolet Rays";
  names["uvalin"] = "Type A UV Radiation";
  names["uvblin"] = "Type B UV Radiation";
  names["uvclin"] = "Type C UV Radiation";
  names["euvlin"] = "Extreme UV Radiation";
  names["xray"] = "X-Rays";
  names["gamma"] = "Gamma Rays";
  names["red"] = "Red Light";
  names["orange"] = "Orange Light";
  names["yellow"] = "Yellow Light";
  names["green"] = "Green Light";
  names["blue"] = "Blue Light";
  names["violet"] = "Violet Light";

  var colors = {};
  colors["radio"] = "yellow";
  colors["micro"] = "orange";
  colors["infrared"] = "red";
  colors["visible"] = "violet";
  colors["xray"] = "purple";
  colors["gamma"] = "black";
  colors["red"] = "red";
  colors["orange"] = "orange";
  colors["yellow"] = "yellow";
  colors["green"] = "green";
  colors["blue"] = "blue";
  colors["violet"] = "violet";

  function logTen(n) {
    return Math.log(n) / Math.log(10);
  }

  var totalLength = logTen(radio.ends) - logTen(gamma.begins);
  var UVLength = logTen(uv.ends) - logTen(uv.begins);
  var visiLength = red.ends - violet.begins;
  var UVLinLength = uv.ends - uv.begins;

  // The following function changes the length of each bar in the spectrum to scale
  function toScale (begins, ends, id) {
    $("#"+id).css("height", function(){
      // if(id[0] === "u" || id[1] === "u"){
      // Converts UV rays to linear scale
      //   var UVHeight = UVLength / totalLength * 100
      //   return (ends - begins) / (uv.ends - uv.begins) * UVHeight + "%";
      // }
      return (logTen(ends) - logTen(begins)) / totalLength * 100 + "%";
    });
  }

  function visiScale (begins, ends, id) {
    $("#" + id).css("height", function(){
      return (ends - begins) / visiLength * 100 + "%";
    });
    // $("#" + id).css("background-color", id);
  }

  function UVScale(begins, ends, id) {
    $("#" + id).css("height", function(){
      return (ends - begins) / UVLinLength * 100 + "%";
    });
  }

  function wavelengthToColor(wavelength) {
    var r,
      g,
      b,
      alpha,
      colorSpace,
      wl = wavelength,
      gamma = 1;

    if (wl >= 380 && wl < 440) {
      R = -1 * (wl - 440) / (440 - 380);
      G = 0;
      B = 1;
    } else if (wl >= 440 && wl < 490) {
      R = 0;
      G = (wl - 440) / (490 - 440);
      B = 1;  
    } else if (wl >= 490 && wl < 510) {
      R = 0;
      G = 1;
      B = -1 * (wl - 510) / (510 - 490);
    } else if (wl >= 510 && wl < 580) {
      R = (wl - 510) / (580 - 510);
      G = 1;
      B = 0;
    } else if (wl >= 580 && wl < 645) {
      R = 1;
      G = -1 * (wl - 645) / (645 - 580);
      B = 0.0;
    } else if (wl >= 645 && wl <= 780) {
      R = 1;
      G = 0;
      B = 0;
    } else {
      R = 0;
      G = 0;
      B = 0;
    }

    // intensty is lower at the edges of the visible spectrum.
    if (wl > 780 || wl < 330) {
      alpha = 0;
    } else if (wl > 700) {
      alpha = (780 - wl) / (780 - 700);
    } else if (wl < 420) {
      alpha = (wl - 330) / (420 - 330);
    } else {
      alpha = 1;
    }

    colorSpace = ["rgba(" + Math.round(R * 255) + "," + Math.round(G * 255) + "," + Math.round(B * 255) + "," + alpha + ")", R, G, B, alpha]

    // colorSpace is an array with 5 elements.
    // The first element is the complete code as a string.  
    // Use colorSpace[0] as is to display the desired color.  
    // use the last four elements alone or together to access each of the individual r, g, b and a channels.  
   
    return colorSpace;
  }
  toScale(radio.begins, radio.ends, "radio");
  toScale(micro.begins, micro.ends, "micro");
  toScale(infrared.begins, infrared.ends, "infrared");
  toScale(visible.begins, visible.ends, "visible");
  toScale(uva.begins, uva.ends, "uva");
  toScale(uvb.begins, uvb.ends, "uvb");
  toScale(uvc.begins, uvc.ends, "uvc");
  toScale(euv.begins, euv.ends, "euv");
  toScale(xray.begins, xray.ends, "xray");
  toScale(gamma.begins, gamma.ends, "gamma");
  visiScale(red.begins, red.ends, "red");
  visiScale(orange.begins, orange.ends, "orange");
  visiScale(yellow.begins, yellow.ends, "yellow");
  visiScale(green.begins, green.ends, "green");
  visiScale(blue.begins, blue.ends, "blue");
  visiScale(violet.begins, violet.ends, "violet");
  UVScale(uva.begins, uva.ends, "uvalin");
  UVScale(uvb.begins, uvb.ends, "uvblin");
  UVScale(uvc.begins, uvc.ends, "uvclin");
  UVScale(euv.begins, euv.ends, "euvlin");
  // $("body").append(visiLength)

  // Event handling follows
  var infobox = $("#infobox");
  var uvspec = $("#UVSpec");
  var uvscale = $("#UV");
  var visiblespec = $("#visiblespec");
  var visiscale = $("#visi");
  var red_light =  $("#red");
  var orange_light = $("#orange");
  var yellow_light = $("#yellow");
  var green_light = $("#green");
  var blue_light = $("#blue");
  var violet_light = $("#violet");
  // red_light.css("background-color", "red");
  // red_light.css("background", "linear-gradient(" + wavelengthToColor(740)[0] + " 0%, "+ wavelengthToColor(650)[0] +" 75%, red)");
  // alert("linear-gradient(" + wavelengthToColor(740)[0] + " 0%, "+ wavelengthToColor(650)[0] +" 75%, "+ wavelengthToColor(620)[0] +" 100%)")
  red_light.css("background", "linear-gradient(" + wavelengthToColor(740)[0] + " 0%, "+ wavelengthToColor(650)[0] +" 75%, "+ wavelengthToColor(620)[0] +" 100%)");
  orange_light.css("background", "linear-gradient(" + wavelengthToColor(620)[0] + " 0%, "+ wavelengthToColor(600)[0] +" 66%, "+ wavelengthToColor(590)[0] +" 100%)");
  yellow_light.css("background", "linear-gradient(" + wavelengthToColor(590)[0] + " 0%, "+ wavelengthToColor(580)[0] +" 66%, "+ wavelengthToColor(570)[0] +" 100%)");
  green_light.css("background", "linear-gradient(" + wavelengthToColor(570)[0] + " 0%, "+ wavelengthToColor(530)[0] +" 53%, "+ wavelengthToColor(495)[0] +" 100%)");
  blue_light.css("background", "linear-gradient(" + wavelengthToColor(495)[0] + " 0%, "+ wavelengthToColor(470)[0] +" 56%, "+ wavelengthToColor(450)[0] +" 100%)");
  violet_light.css("background", "linear-gradient(" + wavelengthToColor(450)[0] + " 0%, "+ wavelengthToColor(380)[0] +" 50%, "+ wavelengthToColor(310)[0] +" 100%)");

  var element;
  $(".spectrum").on("mouseenter touchstart", function(){
    var newcolor = $(this).css("background-color");
    var element_id = $(this).attr("id");
    // alert(newcolor);
    if($(this).hasClass("uv")){
      // Hide visible spectrum and show UV spectrum
      uvscale.css("visibility", "visible");
      uvspec.css("visibility", "visible");
      visiscale.css("visibility", "hidden");
      visiblespec.css("visibility", "hidden");
      infobox.css("border-color", "#556DFF");
    }
    else if(newcolor=="rgb(255, 255, 255)"){
      // Hide UV spectrum and show visible spectrum
      visiscale.css("visibility", "visible");
      visiblespec.css("visibility", "visible");
      uvscale.css("visibility", "hidden");
      uvspec.css("visibility", "hidden");
      infobox.css("border-color", "violet");
    } else {
      visiscale.css("visibility", "hidden");
      visiblespec.css("visibility", "hidden");
      uvscale.css("visibility", "hidden");
      uvspec.css("visibility", "hidden");
      infobox.css("border-color", colors[element_id]);
    }
    // If statement accounts for UV
    if(element_id.length == 3 && element_id !== "red"){
      element_id = "uv";
    }
    // creates message to show inside the displaybox on the right
    var HTMLText = "<h2>" + names[element_id] + "</h2><p>" + descriptions[element_id] + "</p>";
    // appends message
    infobox.html(HTMLText);
    //animation
    element = $("#" + $(this).attr("id"))
    element.animate({
      "width": "11%"
    }, 300)
  }).on("mouseleave touchend", function(){
    // alert($(this).attr("id"))
    /*if($(this).hasClass("uv") && element = $(".uv")){
      return
    } else { */
      element.animate({
        "width": "10%"
      }, 200)
    // }
  });
  $(".zoomline").on("mouseenter touchstart", "div", function(){
    var element_id = $(this).attr("id");
    var HTMLText = "<h2>" + names[element_id] + "</h2><p>" + descriptions[element_id] + "</p>";
    infobox.html(HTMLText);
    infobox.css("border-color", colors[element_id]);
    // $("#"+element_id).css("border", "1px solid black");
    element = $("#" + element_id)
    element.animate({
      "width": "110%"
    }, 300)
  }).on("mouseleave touchend", "div", function(){
    element.animate({
      "width": "100%"
    }, 200)
  });

  // Visible spectrum
  
  // red_light.css("background-color", "blue");
  // alert("linear-gradient(180deg, " + wavelengthToColor(740)[0] + ", blue);");
  
  // alert(red_light.css("background"));
});